### ISSUE TITLE
Disabled menu options on Linux (Kubuntu 18.04 x64)

### ISSUE THREAD

**Issue by misteki** [PixelVision8/PixelVisionOS#146]
Hello! I'm running *PixelVision 8 v0.9.2 Linux*. When executing `Pixel Vision 8 Make.bin.x86_64`, I see all the options in the main menu disabled:

![screenshot_20190301_154805](https://user-images.githubusercontent.com/42174298/53659120-77aade80-3c39-11e9-9f8a-6cf683d46a70.png)

After inspecting a bit, I see that I'm getting these messages in the console:

```
¤ Debug Log Created 20190301154720036

¤ '/PixelVisionOS/Tools/BootTool/' does not have write access

¤ '/PixelVisionOS/Tools/' does not have write access

¤ '/PixelVisionOS/Tools/LoadTool/' does not have write access

¤ '/PixelVisionOS/Tools/' does not have write access

¤ '/PixelVisionOS/Tools/FilePickerTool/' does not have write access
```
I don't know if those are related, but I've given write permissions to everything under these directories, and still no luck. Also tried x86 executable, and running both using `sudo`, but nothing worked. Any ideas? 
Thanks!

**Comment by jessefreeman** [comment]
So you can't do anything on the desktop. Those warnings are unrelated. You'll want to open up the workspace and try to see if the menu is active there. Let me know if you still have issues making a project in the workspace and I can debug this a bit more.
