### ISSUE TITLE
Music Tool (v 0.9.3 Mac)- Index was outside the bounds

### ISSUE THREAD

**Issue by Quentie** [PixelVision8/PixelVisionOS#150]
Music tool won't open when I set all chips to Gameboy and then add music and try to open it.

https://www.dropbox.com/s/phk1rs6u22aw057/IndexWasOutsideTheBoundsMusicTool.mov?dl=0

**Comment by jessefreeman** [comment]
Thanks, I'll look into this. Doing a bit of work on the Music Tool for the next release so I'll be sure to fix this.

**Comment by jessefreeman** [comment]
I've reworked a lot of the underlying music tool's code so this should hopefully be fixed in the next release.
