### ISSUE TITLE
better lua

### ISSUE THREAD

**Issue by Shadowblitz16** [PixelVision8/PixelVisionOS#479]
I have some suggestions for a better lua environment

- loop based execution 
```lua
--init stuff here

while true do
  --update and draw stuff here
  update()
end
```
- assignment operators (requires modifying moonsharp)
`+=`
`-=`
`*=`
`/=`
`%=`
`^=`
`..=`

- auto complete / intellasence

- new keyword or function for tables
```lua
local vec =
{
  x = 0,
  y = 0,
  -- constructor
  _vec = function(this, x, y) 
    this.x = x;
    this.y = y;
  end
  -- add meta method
  _add = function(this, v)
     this.x += v.x
     this.y += v.y
   end
}
-- creates clone and calls the meta methods
local v1 = new vec(0,0) -- requires modifying moonsharp but is cleaner
local v2 = new(vec,0,0) -- doesn't require modifying moonsharp but is less clean
```

**Comment by jessefreeman** [comment]
So I had some of this implemented in the current build of PV8 but will be removed in the next release. The issue is that with the new debugger, I can't match up the pre-compile code modifications to the actual code so you wouldn't be able to properly match things up.

**Comment by Shadowblitz16** [comment]
thats too bad
