### ISSUE TITLE
right click context menus?

### ISSUE THREAD

**Issue by Shadowblitz16** [PixelVision8/PixelVisionOS#483]
please allow right click context menu

this would work if your right click and have...
- no selection but is over a editor or folder explorer.
- you have a selection and are hovering over the selected item

if your not sure what a context menu is then here is a picture
![image](https://user-images.githubusercontent.com/2453707/74799303-023e8080-5285-11ea-962d-c2f5a15f7356.png)

**Comment by jessefreeman** [comment]
I have no plans to add right-click support.

**Comment by Shadowblitz16** [comment]
ok
