### ISSUE TITLE
Code.lua: (86, 0-46), attempt to call a nil value

### ISSUE THREAD

**Issue by Prasparadastra** [PixelVision8/PixelVisionOS#494]
The pixelvision 8 does not boot. What can I do?

![Снимок экрана (154)](https://user-images.githubusercontent.com/62256798/79002469-3afa2800-7b59-11ea-8809-b85e373e5315.png)

**Comment by jessefreeman** [comment]
You should remove the System folder for the Workspace (or rename the Workspace directory in your user folder) and then install the latest version of PV8 so it can rebuild the Workspace folder.
