### ISSUE TITLE
New Sound and New Music generating blank JSON files

### ISSUE THREAD

**Issue by Torbuntu** [PixelVision8/PixelVisionOS#80]
When a new Sound or Music file is generated in a project, the generated file is a blank JSON. 

This makes the music editor unable to open the music file with error: `Index was outside the bounds of the array. `

The empty sound file can still be loaded blank and worked with.

OS: Fedora 29 
PV8 Make v0.9.2

**Comment by jessefreeman** [comment]
This was fixed.
